config/routes.rb
Rails.application.routes.draw do
  get 'test/test'
  root 'homes#home'
  get 'homes/search'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
require 'taglib'
require 'streamio-ffmpeg'

class HomesController < ApplicationController
  def home
    # @auth_wrapper = Discogs::Wrapper.new('Tag editor', user_token: 'BGZOJMVNYSyVnmZyPgiPoPENDuhXQQIczLgEROYc')
    # #binding.pry
    # @data = @auth_wrapper.search(params[:query], per_page: 10, type: :release)
    
    # binding.pry
    
    
    auth_wrapper = Discogs::Wrapper.new('Tag editor', user_token: 'BGZOJMVNYSyVnmZyPgiPoPENDuhXQQIczLgEROYc')
    search = auth_wrapper.search('ATB', per_page: 100, type: :track)
    # binding.pry
    # @image = search.results.first.cover_image
    # @picture = ''
    
    # input_file = FFMPEG::Movie.new('app/assets/music/Ego Acid.flac')
    # output_file = 'app/assets/music/Ego Acid.flac'

    
    # TagLib::FLAC::File.open("app/assets/music/Ego Acid.flac") do |file|
    #   tag = file.tag
    #   data = file.picture_list.first.data
    #   title = file.picture_list.first.description
    #   # binary_data = Base64.decode64(data)
    #   # binding.pry
    #   file = File.new('app/assets/images/Ego_Acid.jpg', 'wb')
    #   file << data
    #   file.close
      # temp_file = Tempfile.new(['image', '.jpg'], encoding: 'ascii-8bit')  # Replace .png with the actual image format
      # temp_file.binmode
      # temp_file << data
      # @picture = temp_file.path
      # temp_file.close

      #binding.pry
      # @picture = data.unpack('B*')
    # end
    #binding.pry
  end

  def search
    @auth_wrapper = Discogs::Wrapper.new('Tag editor', user_token: 'BGZOJMVNYSyVnmZyPgiPoPENDuhXQQIczLgEROYc')
    #binding.pry
    @data = @auth_wrapper.search(params[:query], per_page: 30, type: :release)
    # render json: @data
    #binding.pry
  end

  def release(id)
    @release = @auth_wrapper.get_release(id)
  end
end

app/controllers/test_controller.rb
class TestController < ApplicationController
  def test
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/views/homes/home.html.erb
<%= tag.div data: {controller: 'hello'} do %>
  <p>Tag</p>
<% end %>

<%= tag.h1 'Home', data: {controller: 'homes'} %>
<p>Find me in app/views/home/home.html.erb</p>

<% image_tag('cover', size: "200") %>


<form action='<%= homes_search_url %>' id='search' data-controller="homes">
    <label for='query'>Search for</label>
    <input type='test' name='query'>
    <input type="submit"/>
</form>

<%= form_with url: homes_search_url, method: :get do |form| %>
  <%= form.label :query, "Search for:" %>
  <%= form.text_field :query %>
  <%= form.submit "Search" %>
<% end %>

<% if @data %>
  <table>
    <thead>
      <tr>
        <th>Title</th>
        <th>Artist</th>
        <th>Tracks</th>
        <th>Label</th>
        <th>Country</th>
        <th>Released</th>
        <th>Genre</th>
        <th>Style</th>
      </tr>
    </thead>

    <tbody>
      <% @data.results.each do |d| %>
        <%#binding.pry%>
        <% @release = @auth_wrapper.get_release(d.id) %>
        <tr>
          <td><%= d.title.split('-').last.strip %></td>
          <td><%= d.title.split('-').first.strip %></td>
          <td><%= @release.tracklist.size %></td>
          <td><%= @release.labels.map { |l| l.name }.split.join(', ') %></td>
          <td><%= d.country %></td>
          <td><%= @release.released %></td>
          <td><%= d.genre.split.join(', ').strip %></td>
          <td><%= d.style.split.join(', ').strip %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>No results to display :(</p>
<% end %>


<%# <script>
  document.getElementById('test').onclick = test

  function test() {
    console.log('test');
  }
</script> %>

<%# <script>
  function fetchDataPiece(url) {
    fetch(url)
      .then((response) => {
        console.log(response.json())
      })
      .then(data => {
        console.log(data)
        // Update your HTML content with the received data
        //document.getElementById("data-container").innerHTML += data;
      })
      .catch(error => console.error(error));
  }

  // Call the function repeatedly or based on your logic
  console.log(fetchDataPiece("http://localhost:3000/home/search?query=atb+-+my+dream&commit=Search"));
</script> %>

app/views/homes/search.html.erb
<% if @data %>
  <div class='data-container'>
  <table>
    <thead>
      <tr>
        <th>Image</th>
        <th>Title</th>
        <th>Artist</th>
        <th>Tracks</th>
        <th>Label</th>
        <th>Country</th>
        <th>Released</th>
        <th>Genre</th>
        <th>Style</th>
      </tr>
    </thead>

    <tbody>
      <% @data.results.each do |d| %>
        <%#binding.pry%>
        <% @release = @auth_wrapper.get_release(d.id) %>
        <tr>
          <td><%= image_tag(d.cover_image, size: 100) %></td>
          <td><%= d.title.split('-').last.strip %></td>
          <td><%= d.title.split('-').first.strip %></td>
          <td><%= @release.tracklist&.size %></td>
          <td><%= @release.labels&.map { |l| l&.name }&.split&.join(', ')[..35] %></td>
          <td><%= d.country %></td>
          <td><%= @release.released %></td>
          <td><%= d.genre.split.join(', ').strip %></td>
          <td><%= d.style.split.join(', ').strip %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  </div>
<% else %>
  <p>No results to display :(</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TagEditor</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>